question_data = [
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "medium",
     "question": "DragonForce&#039;s &#039;Through the Fire and Flames&#039; is widely considered to be the hardest song in the Guitar Hero series.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The game &quot;Battlefield 1&quot; takes place during World War I.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                       "question": "Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the body&#039;s inertia.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "The Sonoran Desert is located in eastern Africa.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "St. Louis is the capital of the US State Missouri.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "In the movie The Revenant, DiCaprio&#039;s character hunts down the killer of his son.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
     "question": "The General Motors EV1 was the first street-legal production electric vehicle.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "In &quot;Space Station 13&quot;,  the station has a clown aboard it.", "correct_answer": "True",
     "incorrect_answers": ["False"]}
]

